= Avoid the JAR hell with Java 9 Jigsaw

* Make sure that JAVA_HOME points to a version 9 jdk. I have tested it with the release build.
** On OS X:

    export JAVA_HOME=$(/usr/libexec/java_home 9)

* Build everything and run the app with

    ./gradlew run

* The output will show that 2 versions of the same module have been loaded at the same time:

    Greetings from version ONE!
    Greetings from version TWO!

* You can see the output at travis-ci: https://travis-ci.org/torstenwerner/java-9-no-jar-hell

== Some background

The directories hello1 and hello2 contain almost the same code with just some small modification in the run() method. It
simulates loading 2 different versions of the same module. It would be impossible to use both JARs in the same
classpath. But it is possible to work around that limitation by constructing 2 ModuleLayer instances. That is what main code in
link:src/main/java/com/app/Main.java[Main.java] is doing.

More information about Java 9 Jigsaw module system: http://openjdk.java.net/projects/jigsaw/

I have tested it with gradle 4.0. Older versions of gradle might not work out of the box.

== Continuous Integration thanks to Travis CI

Build image:https://api.travis-ci.org/torstenwerner/java-9-no-jar-hell.svg[status]
at link:https://travis-ci.org/torstenwerner/java-9-no-jar-hell[Travis CI]

== Docker build

Sorry, but the openjdk 9-b181 docker image fails with

    java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty"

Instructions:

    docker pull openjdk:9
    docker build -t java-9-no-jar-hell .
    docker run -it --rm java-9-no-jar-hell

== IntelliJ bug

Switch to JDK 8 if the initial import of the gradle project fails.
Switch to JDK 9 after the initial import.
